# coding: utf-8

"""
    TBU API

    Test Bed Unit API. NOTE all IPv6 address strings are formatted per RFC 5952.  # noqa: E501

    OpenAPI spec version: 1.0.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.neighbor_table_entry import NeighborTableEntry  # noqa: E501
from swagger_client.rest import ApiException


class TestNeighborTableEntry(unittest.TestCase):
    """NeighborTableEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeighborTableEntry(self):
        """Test NeighborTableEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.neighbor_table_entry.NeighborTableEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
