# coding: utf-8

"""
    TBU API

    Test Bed Unit API. NOTE all IPv6 address strings are formatted per RFC 5952.  # noqa: E501

    OpenAPI spec version: 1.0.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.border_router_config import BorderRouterConfig  # noqa: E501
from swagger_client.rest import ApiException


class TestBorderRouterConfig(unittest.TestCase):
    """BorderRouterConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBorderRouterConfig(self):
        """Test BorderRouterConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.border_router_config.BorderRouterConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
