# coding: utf-8

"""
    TBU API

    Test Bed Unit API. NOTE all IPv6 address strings are formatted per RFC 5952.  # noqa: E501

    OpenAPI spec version: 1.0.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.chan_plan_fixed import ChanPlanFixed  # noqa: E501
from swagger_client.rest import ApiException


class TestChanPlanFixed(unittest.TestCase):
    """ChanPlanFixed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChanPlanFixed(self):
        """Test ChanPlanFixed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.chan_plan_fixed.ChanPlanFixed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
