# coding: utf-8

"""
    TBU API

    Test Bed Unit API. NOTE all IPv6 address strings are formatted per RFC 5952.  # noqa: E501

    OpenAPI spec version: 1.0.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unicast_chan_plan import UnicastChanPlan  # noqa: E501
from swagger_client.rest import ApiException


class TestUnicastChanPlan(unittest.TestCase):
    """UnicastChanPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnicastChanPlan(self):
        """Test UnicastChanPlan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unicast_chan_plan.UnicastChanPlan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
