# coding: utf-8

"""
    TBU API

    Test Bed Unit API. NOTE all IPv6 address strings are formatted per RFC 5952.  # noqa: E501

    OpenAPI spec version: 1.0.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ChanPlanRegOp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reg_domain': 'int',
        'op_class': 'int'
    }

    attribute_map = {
        'reg_domain': 'regDomain',
        'op_class': 'opClass'
    }

    def __init__(self, reg_domain=None, op_class=None):  # noqa: E501
        """ChanPlanRegOp - a model defined in Swagger"""  # noqa: E501

        self._reg_domain = None
        self._op_class = None
        self.discriminator = None

        self.reg_domain = reg_domain
        self.op_class = op_class

    @property
    def reg_domain(self):
        """Gets the reg_domain of this ChanPlanRegOp.  # noqa: E501

        Set as specified in TPS US-IE description.  # noqa: E501

        :return: The reg_domain of this ChanPlanRegOp.  # noqa: E501
        :rtype: int
        """
        return self._reg_domain

    @reg_domain.setter
    def reg_domain(self, reg_domain):
        """Sets the reg_domain of this ChanPlanRegOp.

        Set as specified in TPS US-IE description.  # noqa: E501

        :param reg_domain: The reg_domain of this ChanPlanRegOp.  # noqa: E501
        :type: int
        """
        if reg_domain is None:
            raise ValueError("Invalid value for `reg_domain`, must not be `None`")  # noqa: E501

        self._reg_domain = reg_domain

    @property
    def op_class(self):
        """Gets the op_class of this ChanPlanRegOp.  # noqa: E501

        Set as specified in TPS US-IE description.  # noqa: E501

        :return: The op_class of this ChanPlanRegOp.  # noqa: E501
        :rtype: int
        """
        return self._op_class

    @op_class.setter
    def op_class(self, op_class):
        """Sets the op_class of this ChanPlanRegOp.

        Set as specified in TPS US-IE description.  # noqa: E501

        :param op_class: The op_class of this ChanPlanRegOp.  # noqa: E501
        :type: int
        """
        if op_class is None:
            raise ValueError("Invalid value for `op_class`, must not be `None`")  # noqa: E501

        self._op_class = op_class

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChanPlanRegOp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChanPlanRegOp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
