# coding: utf-8

"""
    TBU API

    Test Bed Unit API. NOTE all IPv6 address strings are formatted per RFC 5952.  # noqa: E501

    OpenAPI spec version: 1.0.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MacAddresses(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mac_address_list': 'list[str]'
    }

    attribute_map = {
        'mac_address_list': 'macAddressList'
    }

    def __init__(self, mac_address_list=None):  # noqa: E501
        """MacAddresses - a model defined in Swagger"""  # noqa: E501

        self._mac_address_list = None
        self.discriminator = None

        self.mac_address_list = mac_address_list

    @property
    def mac_address_list(self):
        """Gets the mac_address_list of this MacAddresses.  # noqa: E501

        An array of EUI64 addresses.  # noqa: E501

        :return: The mac_address_list of this MacAddresses.  # noqa: E501
        :rtype: list[str]
        """
        return self._mac_address_list

    @mac_address_list.setter
    def mac_address_list(self, mac_address_list):
        """Sets the mac_address_list of this MacAddresses.

        An array of EUI64 addresses.  # noqa: E501

        :param mac_address_list: The mac_address_list of this MacAddresses.  # noqa: E501
        :type: list[str]
        """
        if mac_address_list is None:
            raise ValueError("Invalid value for `mac_address_list`, must not be `None`")  # noqa: E501

        self._mac_address_list = mac_address_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MacAddresses, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MacAddresses):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
